## **Aula de Regressão Linear**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm
from statsmodels.formula.api import ols

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", 1000)

In [ ]:
df =pd.read_csv("/content/drive/MyDrive/FIAP/Machine Learning & Data Science/2026/Datasets/CarPrice_Assignment.csv")

### **Análise Exploratória**

In [ ]:
df.sample(5)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginetype,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
61,62,1,mazda glc custom,gas,std,two,hatchback,fwd,front,98.8,177.8,66.5,53.7,2385,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10595.0
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.0
149,150,0,subaru dl,gas,turbo,four,wagon,4wd,front,96.9,173.6,65.4,54.9,2650,ohcf,four,108,mpfi,3.62,2.64,7.7,111,4800,23,23,11694.0
156,157,0,toyota mark ii,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,53.0,2081,ohc,four,98,2bbl,3.19,3.03,9.0,70,4800,30,37,6938.0
160,161,0,toyota corona,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,53.0,2094,ohc,four,98,2bbl,3.19,3.03,9.0,70,4800,38,47,7738.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [ ]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [ ]:
df.describe(include="object")

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,enginetype,cylindernumber,fuelsystem
count,205,205,205,205,205,205,205,205,205,205
unique,147,2,2,2,5,3,2,7,7,8
top,peugeot 504,gas,std,four,sedan,fwd,front,ohc,four,mpfi
freq,6,185,168,115,96,120,202,148,159,94

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
fig = px.histogram(df, x="price", nbins=30, title="Distribuição dos preços dos carros", color_discrete_sequence=["blue"])
fig.show()

In [ ]:
categorical_cols = df.select_dtypes(include="object").columns
for col in categorical_cols:
    fig = px.histogram(df, x=col, title=f"Distribuição de {col}", color_discrete_sequence=["purple"])
    fig.show()

In [ ]:
df_num = df.select_dtypes(exclude="object")
corr = df_num.corr()
fig = px.imshow(corr, title="Mapa de calor das correlação")
fig.show()

In [ ]:
fig = px.scatter(df, x="enginesize", y="price", trendline="ols",
                 title="Relação entre tamanho do motor e preço")
fig.show()

In [ ]:
fig = px.box(df, x="carbody", y="price", title="Preço por tipo de carroceria")
fig.show()

In [ ]:
fig = px.scatter(df, x="curbweight", y="citympg", trendline="ols",
                 title="Relação entre peso e consumo urbano")
fig.show()

### **Regressão Linear Simples**

In [ ]:
X = df[["curbweight"]]
y = df["citympg"]

In [ ]:
reg_model = sm.OLS(y, sm.add_constant(X)).fit()

In [ ]:
print(reg_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                citympg   R-squared:                       0.574
Model:                            OLS   Adj. R-squared:                  0.572
Method:                 Least Squares   F-statistic:                     273.2
Date:                Fri, 13 Mar 2026   Prob (F-statistic):           1.93e-39
Time:                        01:17:47   Log-Likelihood:                -588.04
No. Observations:                 205   AIC:                             1180.
Df Residuals:                     203   BIC:                             1187.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         49.5398      1.502     32.992      0.000      46.579      52.501
curbweight    -0.0095      0.001    -16.528      0.000      -0.011      -0.008
==============================================================================
Omnibus:                       33.010   Durbin-Watson:                   1.445
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.059
Skew:                           0.950   Prob(JB):                     6.04e-11
Kurtosis:                       4.379   Cond. No.                     1.31e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.31e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
X = df[["peakrpm"]]
y = df["citympg"]

In [ ]:
reg_model = sm.OLS(y, sm.add_constant(X)).fit()

In [ ]:
print(reg_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                citympg   R-squared:                       0.013
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     2.651
Date:                Fri, 13 Mar 2026   Prob (F-statistic):              0.105
Time:                        01:22:31   Log-Likelihood:                -674.10
No. Observations:                 205   AIC:                             1352.
Df Residuals:                     203   BIC:                             1359.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         33.2010      4.923      6.744      0.000      23.495      42.907
peakrpm       -0.0016      0.001     -1.628      0.105      -0.003       0.000
==============================================================================
Omnibus:                       16.169   Durbin-Watson:                   0.956
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               17.601
Skew:                           0.669   Prob(JB):                     0.000151
Kurtosis:                       3.518   Cond. No.                     5.57e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.57e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

### **Regressão Linear Multivariada**

In [ ]:
X = df[["enginesize", "compressionratio", "price", "highwaympg"]]
y = df["citympg"]

In [ ]:
reg_model = sm.OLS(y, sm.add_constant(X)).fit()

In [ ]:
print(reg_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                citympg   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.949
Method:                 Least Squares   F-statistic:                     956.7
Date:                Fri, 13 Mar 2026   Prob (F-statistic):          3.89e-129
Time:                        01:33:15   Log-Likelihood:                -367.68
No. Observations:                 205   AIC:                             745.4
Df Residuals:                     200   BIC:                             762.0
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -2.7569      0.983     -2.804      0.006      -4.695      -0.818
enginesize           0.0068      0.005      1.308      0.192      -0.003       0.017
compressionratio     0.1446      0.029      4.995      0.000       0.087       0.202
price            -7.614e-05   2.86e-05     -2.665      0.008      -0.000   -1.98e-05
highwaympg           0.8669      0.024     36.659      0.000       0.820       0.914
==============================================================================
Omnibus:                       13.061   Durbin-Watson:                   1.169
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.361
Skew:                           0.438   Prob(JB):                     0.000170
Kurtosis:                       4.124   Cond. No.                     1.48e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.48e+05. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')